apiVersion: v1
kind: Template
metadata: {}
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: aggregated-api-ex
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: aggregated-api-ex:latest
    runPolicy: Serial
    source:
      contextDir: src
      git:
        uri: https://github.com/fbac/aggregated-api-ex
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:8
          namespace: openshift
      type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: aggregated-api-ex
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/aggregated-api-ex/aggregated-api-ex:latest
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: aggregated-api-ex-serving-cert
    name: aggregated-api-ex
  spec:
    ports:
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: aggregated-api-ex
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: aggregated-api-ex
  spec:
    replicas: 1
    selector:
      deploymentconfig: aggregated-api-ex
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: aggregated-api-ex
      spec:
        containers:
        - image: aggregated-api-ex:latest
          imagePullPolicy: Always
          name: aggregated-api-ex
          ports:
          - containerPort: 8443
            protocol: TCP
          restartPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
          volumeMounts:
          - mountPath: /opt/app-root/src/ssl
            name: serving-cert
        volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: aggregated-api-ex-serving-cert
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - aggregated-api-ex
        from:
          kind: ImageStreamTag
          name: aggregated-api-ex:latest
type: ImageChange
